spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:    #开发环境
    name: mhservicecloud-config-mh-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: mhservicecloud-config-mh-test
